package com.fundtracker.security;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fundtracker.model.User;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.Collection;
import java.util.List;

public class UserDetailsImpl implements UserDetails {

    private final String id;
    private final String uid;
    private final String username;
    @JsonIgnore private final String password;
    private final String userType;
    private final Collection<? extends GrantedAuthority> authorities;

    public UserDetailsImpl(String id, String uid, String username, String password,
                           String userType, Collection<? extends GrantedAuthority> authorities) {
        this.id          = id;
        this.uid         = uid;
        this.username    = username;
        this.password    = password;
        this.userType    = userType;
        this.authorities = authorities;
    }

    public static UserDetailsImpl build(User user) {
        List<GrantedAuthority> authorities = List.of(
                new SimpleGrantedAuthority("ROLE_" + user.getUserType().toUpperCase())
        );
        return new UserDetailsImpl(
                user.getId(),
                user.getUid(),
                user.getUsername(),
                user.getPassword(),
                user.getUserType(),
                authorities
        );
    }

    // Custom getters — were previously generated by Lombok @Getter; now explicit
    public String getId()       { return id; }
    public String getUid()      { return uid; }
    public String getUserType() { return userType; }

    // UserDetails interface implementations
    @Override public Collection<? extends GrantedAuthority> getAuthorities() { return authorities; }
    @Override public String getPassword()                { return password; }
    @Override public String getUsername()                { return username; }
    @Override public boolean isAccountNonExpired()       { return true; }
    @Override public boolean isAccountNonLocked()        { return true; }
    @Override public boolean isCredentialsNonExpired()   { return true; }
    @Override public boolean isEnabled()                 { return true; }
}
